---

- name: Check if calio is installed
  ansible.builtin.shell: kubectl get pods --all-namespaces | grep calico
  delegate_to: "{{ groups['kubemaster'][0] }}"
  run_once: true
  register: calio_namespace_exist
  ignore_errors: true

- block:
    - name: Install Tigera Calico operator
      ansible.builtin.command: kubectl create -f https://raw.githubusercontent.com/projectcalico/calico/v3.26.3/manifests/tigera-operator.yaml
      delegate_to: "{{ groups['kubemaster'][0] }}"
      run_once: true
    - name: Download calio.yaml
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/projectcalico/calico/{{ calico_version }}/manifests/custom-resources.yaml
        dest: /root/calico-{{ calico_version }}.yaml
      delegate_to: "{{ groups['kubemaster'][0] }}"
      run_once: true

    - name: get csi snapshotter version
      command: >
        awk -F: '/csi-snapshotter/{print substr($3, 1, length($3)-1)}' "/root/calico-{{ calico_version }}.yaml"
      delegate_to: "{{ groups['kubemaster'][0] }}"
      register: csi_snapshotter_version
      run_once: true

    - name: Add KUBELET_ROOT_DIR env var
      ansible.builtin.lineinfile:
        path: /root/calico-{{ calico }}.yaml
        insertafter: 'value: \"calico/csi-snapshotter:{{csi_snapshotter_version.stdout}}\"'
        line: '          - name: KUBELET_ROOT_DIR'
      delegate_to: "{{ groups['kubemaster'][0] }}"
      run_once: true

    - name: Add KUBELET_ROOT_DIR env var, set value
      ansible.builtin.lineinfile:
        path: /root/calico-{{ calico }}.yaml
        insertafter: '- name: KUBELET_ROOT_DIR'
        line: '            value: "/var/lib/kubelet"'
      delegate_to: "{{ groups['kubemaster'][0] }}"
      run_once: true

    - name: Install calico
      ansible.builtin.command: kubectl apply -f /root/calico-{{ calico_version }}.yaml
      delegate_to: "{{ groups['kubemaster'][0] }}"
      run_once: true

  when: 
    - inventory_hostname in groups['kubemaster']
    - longorn_namespace_exist.rc == 1