---
- hosts: kubemaster
  become: yes
  remote_user: vagrant
  roles: 
    - role: ansible-k8s
  vars_files:
    - vars.yaml

- hosts: kubeworker 
  become: yes
  remote_user: vagrant
  roles: 
    -  role: ansible-k8s
  vars_files:
    - vars.yaml