---
- hosts: kubemaster
  become: yes
  remote_user: vagrant
  roles: 
    - role: ansible-role-linux-kubernetes
  vars_files:
    - vars.yaml

- hosts: kubeworker 
  become: yes
  remote_user: vagrant
  roles: 
    -  role: ansible-role-linux-kubernetes
  vars_files:
    - vars.yaml